# Generated by Django 3.1.5 on 2021-04-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_stock_ticker', models.CharField(max_length=40)),
                ('user_stock_quantity', models.CharField(max_length=40)),
                ('user_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample_app.accountholder')),
            ],
        ),
    ]
